local Consts = {}
Consts.CAMERA_Y_OFFSET = 18
Consts.CAMERA_Z_OFFSET = -12
Consts.CAMERA_X_ANGLE = 42
Consts.SCENE_VIEW_OFFSET = Vector3.New(0, 0, 60)
Consts.FOLLOW_VIEW_OFFSET = Vector3.New(0, Consts.CAMERA_Y_OFFSET, Consts.CAMERA_Z_OFFSET)
Consts.SCENE_CHUNK_SIZE = 66
Consts.ENGAGING_SPEED = 6
Consts.DEFAULT_REP_FACTOR = 0.5
Consts.DEFAULT_ATT_FACTOR = 0.02
Consts.VIBRATE_CD = 1
Consts.END_ZOMBIE_LIMIT = 50
Consts.END_UNITS_PER_LINE = 12
Consts.END_UNITS_LINE_LIMIT = 13
return Consts
