namespace GME;

public enum ITMG_NETWORK_QUALITY
{
	ITMG_NETWORK_QUALITY_UNKNOWN,
	ITMG_NETWORK_QUALITY_EXCELLENT,
	ITMG_NETWORK_QUALITY_GOOD,
	ITMG_NETWORK_QUALITY_POOR,
	ITMG_NETWORK_QUALITY_BAD,
	ITMG_NETWORK_QUALITY_VBAD,
	ITMG_NETWORK_QUALITY_DOWN
}
