namespace GME;

public enum ITMG_KARAOKE_TYPE
{
	ITMG_KARAOKE_TYPE_0,
	ITMG_KARAOKE_TYPE_1,
	ITMG_KARAOKE_TYPE_2,
	ITMG_KARAOKE_TYPE_3,
	ITMG_KARAOKE_TYPE_4,
	ITMG_KARAOKE_TYPE_5,
	ITMG_KARAOKE_TYPE_6,
	ITMG_KARAOKE_TYPE_7,
	ITMG_KARAOKE_TYPE_8,
	ITMG_KARAOKE_TYPE_9,
	ITMG_KARAOKE_TYPE_10,
	ITMG_KARAOKE_TYPE_11
}
