namespace GME;

public enum ITMG_VOICE_TYPE
{
	ITMG_VOICE_TYPE_ORIGINAL_SOUND,
	ITMG_VOICE_TYPE_KINDER_GARTEN,
	ITMG_VOICE_TYPE_LOLITA,
	ITMG_VOICE_TYPE_UNCLE,
	ITMG_VOICE_TYPE_HEAVY_MENTAL,
	ITMG_VOICE_TYPE_INFLUENZA,
	ITMG_VOICE_TYPE_DIALECT,
	ITMG_VOICE_TYPE_CAGED_ANIMAL,
	ITMG_VOICE_TYPE_DEAD_FATBOY,
	ITMG_VOICE_TYPE_STRONG_CURRENT,
	ITMG_VOICE_TYPE_HEAVY_MACHINE,
	ITMG_VOICE_TYPE_INTANGIBLE,
	ITMG_VOICE_TYPE_PIGSY,
	ITMG_VOICE_TYPE_HULK
}
