namespace GME;

public enum ITMG_EVENT_ID_USER_UPDATE
{
	ITMG_EVENT_ID_USER_ENTER = 1,
	ITMG_EVENT_ID_USER_EXIT,
	ITMG_EVENT_ID_USER_MIC_OPENED,
	ITMG_EVENT_ID_USER_MIC_CLOSED,
	ITMG_EVENT_ID_USER_HAS_AUDIO,
	ITMG_EVENT_ID_USER_NO_AUDIO
}
