require("Framework.Common.BaseClass")
require("Framework.Common.DataClass")
require("Framework.Common.ConstClass")
Config = require("Global.Config")
InterfaceConfig = require("Global.InterfaceConfig")
Singleton = require("Framework.Common.Singleton")
Updatable = require("Framework.Common.Updatable")
require("Framework.Common.Eventable")
LocalController = require("Common.LocalController")
Logger = require("Framework.Logger.Logger")
PostEventLog = require("Framework.Logger.PostEventLog")
BIManager = require("Framework.Logger.BIManager")
require("Framework.Updater.Coroutine")
EventId = require("Framework.UI.Message.EventId")
EventManager = require("Framework.UI.Message.EventManager")
UITimeManager = require("Framework.UI.Time.UITimeManager")
NameCount = 0
DataCenter = require("DataCenter.DataCenter")
RenderSetting = require("Render.RenderSetting")
EnumType = require("Global.EnumType")
require("Global.EnumSoundType")
ArrowTipEnumtype = require("DataCenter.ArrowTipParamManager.ArrowTipEnumtype")
PostType = require("Chat.Constant.PostType")
GameDialogDefine = require("Global.GameDialogDefine")
ConstDefine = require("Global.ConstDefine")
BattlefieldConfig = require("Scene.Battlefield.BattlefieldConfig")
PathUtil = require("Framework.Common.PathUtil")
UIBaseCtrl = require("Framework.UI.Base.UIBaseCtrl")
UIGameObjectWrap = require("Framework.UI.Base.UIGameObjectWrap")
UIBaseComponent = require("Framework.UI.Base.UIBaseComponent")
UIBaseContainer = require("Framework.UI.Base.UIBaseContainer")
UIAsyncContainer = require("Framework.UI.Base.UIAsyncContainer")
UIAsyncNode = require("Framework.UI.Base.UIAsyncNode")
UIAsyncLoaderBridge = require("Framework.UI.Base.UIAsyncLoaderBridge")
UIBaseView = require("Framework.UI.Base.UIBaseView")
UIAsyncDataContainer = require("Framework.UI.Base.UIAsyncDataContainer")
UIAsyncProxy = require("Framework.UI.Base.UIAsyncProxy")
UILayerComponent = require("Framework.UI.Component.UILayerComponent")
UICanvas = require("Framework.UI.Component.UICanvas")
UITextMeshProUGUI = require("Framework.UI.Component.UITextMeshProUGUI")
UITextMeshProUGUIEx = require("Framework.UI.Component.UITextMeshProUGUIEx")
UIText = require("Framework.UI.Component.UIText")
UIOutline = require("Framework.UI.Component.UIOutline")
UITweenNumberText = require("Framework.UI.Component.UITweenNumberText")
UINewText = require("Framework.UI.Component.UINewText")
UIImage = require("Framework.UI.Component.UIImage")
UIRawImage = require("Framework.UI.Component.UIRawImage")
UICommonHead = require("Framework.UI.Component.UICommonHead")
UIPlayerHead = require("Framework.UI.Component.UIPlayerHead")
CircleImage = require("Framework.UI.Component.CircleImage")
RadarImage = require("Framework.UI.Component.RadarImage")
UISlider = require("Framework.UI.Component.UISlider")
UIInput = require("Framework.UI.Component.UIInput")
UIInputCommonType = require("Framework.UI.Component.UIInputCommonType")
UIButton = require("Framework.UI.Component.UIButton")
UIButton_LongPress = require("Framework.UI.Component.UIButton_LongPress")
UIEventTrigger = require("Framework.UI.Component.UIEventTrigger")
UILongPressTrigger = require("Framework.UI.Component.UILongPressTrigger")
UIToggle = require("Framework.UI.Component.UIToggle")
UICommonTabGroupGenerator = require("Framework.UI.Component.UICommonTabGroupGenerator")
UIUnlimitedScrollView = require("Framework.UI.Component.UIUnlimitedScrollView")
UIAnimator = require("Framework.UI.Component.UIAnimator")
UISimpleAnimation = require("Framework.UI.Component.UISimpleAnimation")
UIScrollRect = require("Framework.UI.Component.UIScrollRect")
TouchInputController2 = require("Framework.UI.Component.TouchInputController2")
UIScrollRectEventTrigger = require("Framework.UI.Component.UIScrollRectEventTrigger")
UIBoxCollider2D = require("Framework.UI.Component.UIBoxCollider2D")
UIScrollView = require("Framework.UI.Component.UIScrollView")
UIScrollViewSimple = require("Framework.UI.Component.UIScrollViewSimple")
UIHorizontalOrVerticalLayoutGroup = require("Framework.UI.Component.UIHorizontalOrVerticalLayoutGroup")
UICanvasGroup = require("Framework.UI.Component.UICanvasGroup")
UIShadow = require("Framework.UI.Component.UIShadow")
UIDropdown = require("Framework.UI.Component.UIDropdown")
UILayoutElement = require("Framework.UI.Component.UILayoutElement")
UILoopListView2 = require("Framework.UI.Component.UILoopListView2")
UILoopListViewSimple = require("Framework.UI.Component.UILoopListViewSimple")
HorizontalInfinityScrollView = require("Framework.UI.Component.HorizontalInfinityScrollView")
GridInfinityScrollView = require("Framework.UI.Component.GridInfinityScrollView")
UIScrollPage = require("Framework.UI.Component.UIScrollPage")
UIExtraEffect = require("UI.UIExtraEffect.UIExtraEffect")
UICareerLabel = require("UI.UIPlayerLevel.Component.UICareerLabel")
UIAlOfficialPos = require("UI.UIPlayerLevel.Component.UIAlOfficialPos")
UIVipLevelBadge = require("UI.UIPlayerLevel.Component.UIVipLevelBadge")
GetHDRIntensity = require("Framework.UI.Component.GetHDRIntensity")
UIEmpty4Raycast = require("Framework.UI.Component.UIEmpty4Raycast")
UICenterOnChild = require("Framework.UI.Component.UICenterOnChild")
UIScrollRectCenter = require("Framework.UI.Component.UIScrollRectCenter")
UIDynamicVerticleScrollRect = require("Framework.UI.Component.UIDynamicVerticleScrollRect")
UIDynamicVerticleScrollRectEx = require("Framework.UI.Component.UIDynamicVerticleScrollRectEx")
UICommonNameLayout = require("Framework.UI.Component.UICommonNameLayout")
UIGradient = require("Framework.UI.Component.UIGradient")
UIGridLayoutGroup = require("Framework.UI.Component.UIGridLayoutGroup")
UILoopGridView = require("Framework.UI.Component.UILoopGridView")
UISpine = require("Framework.UI.Component.UISpine")
UIVfx = require("Framework.UI.Component.UIVfx")
UISliderGroup = require("Framework.UI.Component.UISliderGroup")
UISliderBtnInputField = require("Framework.UI.Component.UISliderBtnInputField")
UISpineLogic = require("Framework.UI.Component.UISpineLogic")
UICommonRedPoint = require("Framework.UI.Component.UICommonRedPoint")
UIViewSkinBridge = require("Framework.UI.Component.UIViewSkinBridge")
UICommonTabGroupGenerator = require("Framework.UI.Component.UICommonTabGroupGenerator")
UIModelView = require("Framework.UI.Component.UIModelView")
UIGameObjectPoolRoot = require("Framework.UI.Component.UIGameObjectPoolRoot")
UILayer = require("Framework.UI.UILayer")
UIWindow = require("Framework.UI.UIWindow")
UIManager = require("Framework.UI.UIManager")
UIWindowNames = require("UI.Config.UIWindowNames")
UIConfig = require("UI.Config.UIConfig")
UIComponentPoolManager = require("Framework.UI.UIComponentPoolManager")
require("Util.GameQualityEnums")
require("Util.GameQualityEnums_V1")
require("Util.GameQualitySettings")
Timer = require("Framework.Updater.Timer")
TimerManager = require("Framework.Updater.TimerManager")
UpdateManager = require("Framework.Updater.UpdateManager")
MsgDefines = require("Net.Config.MsgDefines")
SFSBaseMessage = require("Net.SFSBaseMessage")
SFSNetwork = require("Net.SFSNetwork")
SFSObject = require("Common.Data.SFSObject")
SFSArray = require("Common.Data.SFSArray")
LoadingView = require("Loading.LoadingView")
LuaDBInterface = require("Common.LuaDBInterface")
require("Chat.initChat")
EventManager:GetInstance()
UIManager:GetInstance()
UpdateManager:GetInstance()
DOTween = CS.DG.Tweening.DOTween
Screen = CS.UnityEngine.Screen
Setting = CS.GameEntry.Setting
PBController = require("Net.Proto.PBController")
Base64 = require("Framework.Common.base64")
CS.GameEntry.Localization:SetSuportedLanguages(SuportedLanguages)
math.randomseed(SafeLocalOsTime())
UpdateManager:GetInstance():Startup()
TimerManager:GetInstance():Startup()
UIManager:GetInstance():Startup()
CSharpCallLuaInterface = require("Util.CSharpCallLuaInterface")
