public enum AnoReportType
{
	REPORT_TYPE_CHEAT = 1,
	REPORT_TYPE_ABUSE_BUGS = 2,
	REPORT_TYPE_NEGATIVE_GAME = 3,
	REPORT_TYPE_SPREAD_ADS = 4,
	REPORT_TYPE_INSULTING = 5,
	REPORT_TYPE_VIOLATING_INFO = 6,
	REPORT_TYPE_OTHERS = 99
}
