local UIBattleResultJeepAdventureVictoryCtrl = BaseClass("UIBattleResultJeepAdventureVictoryCtrl", UIBaseCtrl)

function UIBattleResultJeepAdventureVictoryCtrl:CloseSelf()
  UIManager:GetInstance():DestroyWindow(UIWindowNames.UIBattleResultJeepAdventureVictory)
end

return UIBattleResultJeepAdventureVictoryCtrl
