local LWUIZoneMobilizationSuppliesRecordCtrl = BaseClass("LWUIZoneMobilizationSuppliesRecordCtrl", UIBaseCtrl)

function LWUIZoneMobilizationSuppliesRecordCtrl:CloseSelf()
  UIManager:GetInstance():DestroyWindow(UIWindowNames.LWUIZoneMobilizationSuppliesRecord)
end

return LWUIZoneMobilizationSuppliesRecordCtrl
