ChatBIEnum = {
  IM_GET_SERVER_LIST_REQUEST = "IM_REQUEST_SERVER_LIST",
  IM_GET_SERVER_LIST_SUCCESS = "IM_GET_SERVER_LIST_SUCCESS",
  IM_GET_SERVER_LIST_ERROR = "IM_GET_SERVER_LIST_ERROR",
  IM_GET_SERVER_LIST_REFUSE = "IM_GET_SERVER_LIST_REFUSE",
  IM_CONNECT_AND_LOGIN_REQUEST = "IM_CONNECT_AND_LOGIN_REQUEST",
  IM_CONNECT_AND_LOGIN_SUCCESS = "IM_CONNECT_AND_LOGIN_SUCCESS",
  IM_CONNECT_AND_LOGIN_ERROR = "IM_CONNECT_AND_LOGIN_ERROR",
  IM_COMMAND_SEND = "IM_COMMAND_SEND",
  IM_COMMAND_BACK = "IM_COMMAND_BACK",
  IM_ENTER_CHAT_PAGE = "IM_ENTER_CHAT_PAGE",
  CHAT_SERVER_DISCONNECT = "CHAT_SERVER_DISCONNECT",
  ChatMsgSendClick = "chat_send_click"
}
ChatBI_CmdWhiteList = {
  [ChatMsgDefines.UserSetInfo] = true,
  [ChatMsgDefines.GetCustomRoomList] = true,
  [ChatMsgDefines.RoomJoinMulti] = true,
  [ChatMsgDefines.HistoryRoomsV2] = true,
  [ChatMsgDefines.HistoryRoomV2] = true,
  [ChatMsgDefines.ChatRoom] = true
}
