local UIPersonalArmsCalendarExchangeConfirmCtrl = BaseClass("UIPersonalArmsCalendarExchangeConfirmCtrl", UIBaseCtrl)

function UIPersonalArmsCalendarExchangeConfirmCtrl:CloseSelf()
  UIManager:GetInstance():DestroyWindow(UIWindowNames.UIPersonalArmsCalendarExchangeConfirmView)
end

return UIPersonalArmsCalendarExchangeConfirmCtrl
