local LWUIZoneMobilizationBoxRewardPreviewCtrl = BaseClass("LWUIZoneMobilizationBoxRewardPreviewCtrl", UIBaseCtrl)

function LWUIZoneMobilizationBoxRewardPreviewCtrl:CloseSelf()
  UIManager:GetInstance():DestroyWindow(UIWindowNames.LWUIZoneMobilizationBoxRewardPreview)
end

return LWUIZoneMobilizationBoxRewardPreviewCtrl
