print("Common main start...")
ProfilerUtil = require("Util.ProfilerUtil")
require("Common.Tools.import")
require("Common.LuaUtil")
require("Common.TableUtil")
require("Common.TableAdvUtil")
require("Common.StringUtil")
require("Common.FuncUtil")
require("Common.BitOps")
Mathf = require("Common.Tools.UnityEngine.Mathf")
Vector2 = require("Common.Tools.UnityEngine.Vector2")
Vector3 = require("Common.Tools.UnityEngine.Vector3")
Vector4 = require("Common.Tools.UnityEngine.Vector4")
Quaternion = require("Common.Tools.UnityEngine.Quaternion")
Color = require("Common.Tools.UnityEngine.Color")
Ray = require("Common.Tools.UnityEngine.Ray")
Bounds = require("Common.Tools.UnityEngine.Bounds")
RaycastHit = require("Common.Tools.UnityEngine.RaycastHit")
Touch = require("Common.Tools.UnityEngine.Touch")
LayerMask = require("Common.Tools.UnityEngine.LayerMask")
Plane = require("Common.Tools.UnityEngine.Plane")
Time = require("Common.Tools.UnityEngine.Time")
Object = require("Common.Tools.UnityEngine.Object")
Color32 = require("Common.Tools.UnityEngine.Color32")
list = require("Common.Tools.list")
arrayV2 = require("Common.Tools.arrayV2")
arrayV3 = require("Common.Tools.arrayV3")
LuaCSharpArray = require("Common.Tools.LuaCSharpArray.LuaCSharpArray")
require("Common.Tools.event")
require("Common.Debug.DebugConfig")
estimateTableSize = require("Common.Debug.EstimateTableSize")
